[project]
name = "pyfmrheo"
version = "0.1.0"

[build-system]
requires = [
    "setuptools>=61.0", 
    "numpy", 
    "scipy",
    "lmfit",
    "pyfmreader",
    "requests"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]